### ISSUE TITLE
Please remove autogenerated files from the source tree

### ISSUE THREAD

**Issue by smoe** [bxlab/bx-python#14]
Hello,

The files created by cython and anything else that is generated in an automated fashion please do not redistribute with source tree. This way one spots more easily when something fails and it allows the now freshly generated Debian package to work with the release of yours directly. Otherwise those files would first need to be removed as the upstream files are not allowed to be changed during the build if it is not a formal patch.

Here the files coming to our attention:

        lib/bx/_seqmapping.c
        lib/bx/align/_core.c
        lib/bx/align/_epo.c
        lib/bx/align/sitemask/_cpg.c
        lib/bx/arrays/array_tree.c
        lib/bx/arrays/bed.c
        lib/bx/arrays/wiggle.c
        lib/bx/bbi/bbi_file.c
        lib/bx/bbi/bigbed_file.c
        lib/bx/bbi/bigwig_file.c
        lib/bx/bbi/bpt_file.c
        lib/bx/bbi/cirtree_file.c
        lib/bx/bitset.c
        lib/bx/intervals/cluster.c
        lib/bx/intervals/intersection.c
        lib/bx/intseq/ngramcount.c
        lib/bx/misc/_seekbzip2.c
        lib/bx/misc/bgzf.c
        lib/bx/motif/_pwm.c
        lib/bx/pwm/_position_weight_matrix.c
        lib/bx/seq/_nib.c
        lib/bx/seq/_twobit.c
        lib/bx/bbi/bbi_file.h

Many thanks and regards,

Steffen

**Comment by jxtx** [comment]
We deliberately include these files in the distribution so that the end-user does not need to have Cython.

**Comment by mbargull** [comment]
I support @smoe's request. To quote myself from #25:
Though I would advice against it since they needn't be under source control and are always bound to get out of sync again. They could/should be recreated on-the-fly when building the distribution, i.e., `python setup.py build_ext sdist` for source distributions.

**Comment by nsoranzo** [comment]
This was fixed in #25.
