### ISSUE TITLE
Is there documentation for bx-python outside the codebase? 

### ISSUE THREAD

**Issue by alexlenail** [bxlab/bx-python#16]
the wiki page redirects to the repo main page which is weird...

**Comment by dylanmmarshall** [comment]
I too, would like it if there was further documentation...

**Comment by dylanmmarshall** [comment]
I noticed there was an initial attempt at sphinx documentation https://github.com/bxlab/bx-python/tree/master/doc/source/static but wasn't followed up on.

**Comment by alexlenail** [comment]
@DylanM-Marshall if you're in the genomics space, fastinterval depends on this and has better docs. http://fastinterval.readthedocs.io/en/latest/

**Comment by dylanmmarshall** [comment]
That's awesome and all, but my files are primarily bigwig, not fasta - even if conversion between the two is relatively simple.

**Comment by jxtx** [comment]
We can rig up readthedocs to generate what is there. But more should be
written.

**Comment by dylanmmarshall** [comment]
@jxtx That would be super cool

**Comment by jxtx** [comment]
http://bx-python.readthedocs.io/en/latest/

(it's a start)

**Comment by dylanmmarshall** [comment]
Great things have small beginnings!

**Comment by jxtx** [comment]
Okay, now we are getting somewhere. Docs should be building for all modules including Cython ones. Now just need to fill in some of those doc strings. 

http://bx-python.readthedocs.io/en/latest/lib/bx.bbi.bigwig_file.html
