### ISSUE TITLE
pip install

### ISSUE THREAD

**Issue by hmontenegro** [bxlab/bx-python#20]
bx-python does not install completely with `pip install bx-python`, as some shared libraries are not compiled:

bbi_file.so, bigbed_file.so, bigwig_file.so, bpt_file.so, cirtree_file.so

This causes problems with other packages, e.g. [this](https://sourceforge.net/p/crossmap/tickets/1/) issue with CrossMap.

One needs to download from PyPI and install with `pip install bx-python-0.7.3.tar.gz`

**Comment by TyberiusPrime** [comment]
Also, for pip to evaluate the requirements, numpy must have been installed previously, preventing install in a clean virtual environment.

**Comment by nsoranzo** [comment]
Installing from wheels (which are available for recent releases on PyPI) should solve this.
