### ISSUE TITLE
Could you please add 0.8.0 to pypi and the releases page? 

### ISSUE THREAD

**Issue by endrebak** [bxlab/bx-python#24]
I'd like to update the bx-python bioconda recipe to support py3 since bx-python now supports it.

**Comment by mbargull** [comment]
If #25 is functional and accepted, I'd like to concur 😄. @endrebak, any reason you closed this?

**Comment by endrebak** [comment]
bx works (for me) with py3 when installed with pypi, but does not build on conda. So there is no point in adding it to conda.

**Comment by mbargull** [comment]
That installation won't be complete, though. If you try to `python -c 'import bx.seq'` you should get some `ModuleNotFoundError`.

**Comment by endrebak** [comment]
I only use intervaltrees 😳
