### ISSUE TITLE
install problems without bitset.c file

### ISSUE THREAD

**Issue by LujingF** [bxlab/bx-python#33]
Hi, I  use the command " python setup.py install" to install bx-python on linux server, however, I got "gcc: lib/bx/bitset.c: No such file or directory" error when the scripts running. So, what should I do? My system environment is : python 2.7(anaconda2), gcc version 4.4.7. Thanks a lot.

**Comment by jxtx** [comment]
bx-python needs Cython to build. If you use the latest HEAD this should be installed automatically.

**Comment by tan5251** [comment]
I have the same problem. What's the meaning of "use the latest HEAD ". Thanks.

**Comment by nsoranzo** [comment]
@tan5251 We provide wheels on PyPI and conda packages, have you tried to install those?

**Comment by tan5251** [comment]
Thanks for your quick reply. I have successfully installed by conda.
