### ISSUE TITLE
Add link to ReadTheDocs in Github README

### ISSUE THREAD

**Issue by scottgigante** [bxlab/bx-python#34]
Please add a link to https://bx-python.readthedocs.io/en/latest/ in the README, I only found it because I recognised the file structure in the `doc` folder. You can add a shield as follows:
[![Read the Docs](https://img.shields.io/readthedocs/phate.svg)](https://phate.readthedocs.io/)

```
[![Read the Docs](https://img.shields.io/readthedocs/bx-python.svg)](https://bx-python.readthedocs.io/)
```

Thanks!

**Comment by jxtx** [comment]
Thanks. Build is failing unfortunately.
