### ISSUE TITLE
No module named 'UserDict' when import bx.intervals.io

### ISSUE THREAD

**Issue by mikpom** [bxlab/bx-python#37]
Getting `ImportError: No module named 'UserDict'` when running

    from bx.intervals import io
    
I am using Python 3.5.2 and it looks like 2-to-3 migration
issues. Does a workaround exist?

**Comment by nsoranzo** [comment]
bx-python does not use `UserDict` since v0.8.0, are you sure you are using the latest release? I cannot reproduce this issue.

**Comment by mikpom** [comment]
I was using old version. Fixed in 0.8.0.
Closed.
