### ISSUE TITLE
Minimal Python version

### ISSUE THREAD

**Issue by superbobry** [bxlab/bx-python#5]
Hi, I've noticed that `setup.py` forbids installing `bx-python` on Python <2.4. However, from the code it seems the minimal version is at least 2.5, because of 

```
lib/bx/align/epo.py
4:from __future__ import with_statement
```

which [was added](https://docs.python.org/2/library/__future__.html) in 2.5.0.

Could you please clarify the minimum Python version requirements?

**Comment by nsoranzo** [comment]
For the next release the minimum Python version will be 2.7.

**Comment by superbobry** [comment]
I see, thanks!
