### ISSUE TITLE
Wheel for Python 3.8

### ISSUE THREAD

**Issue by sebastiencdj** [bxlab/bx-python#51]
Hello,

Could it be possible to have a wheel for python 3.8?

Thanks!

**Comment by nsoranzo** [comment]
Thanks for the suggestion! Wheels are built on Travis CI with cibuildwheel, which is still adding support for Python 3.8: https://github.com/joerick/cibuildwheel/issues/170 .
We'll release 3.8 wheels as soon as that is available.

**Comment by nsoranzo** [comment]
I've just released v0.8.6 with wheels for Python 2.7, 3.5, 3.6, 3.7 and 3.8.
