### ISSUE TITLE
Add support to release linux aarch64 wheels

### ISSUE THREAD

**Issue by odidev** [bxlab/bx-python#78]
Problem
---------
On aarch64, `pip install bx-python` builds the wheels from source code and then installs it. It requires the user to have a development environment installed on their system. Also, it takes more time to build the wheels than downloading and extracting the wheels from PyPI.

Resolution
-----------
On aarch64, `pip install bx-python` should download the wheels from PyPI.

@nsoranzo, Please let me know your interest in releasing aarch64 wheels. I can help with this.

**Comment by nsoranzo** [comment]
Wheels for manylinux aarch64 will be available from the next release.
