### ISSUE TITLE
ERROR Missing dependencies: oldest-supported-numpy

### ISSUE THREAD

**Issue by brobr** [bxlab/bx-python#88]
Hi, compiling from source breaks on the line
> requires = ["cython", "oldest-supported-numpy", "setuptools", "wheel"]

in the 'pyproject.toml' when bx-python is compiled from source using

>python3 -m build --no-isolation
python3 -m installer -d "$PKG" dist/*.whl

Replacing "oldest-supported-numpy" with "numpy" makes it work.

**Comment by nsoranzo** [comment]
@brobr Thanks for reporting your issue, would you mind sharing what's the use case here? I've put a lot of effort in building ready-to-use wheels on PyPI for Python 3.7 to 3.11.

Secondarily, we'd need more information to reproduce the issue (e.g. Python version, operating system, a traceback).
This works absolutely fine for me in a Python 3.8 virtual env on Ubuntu 20.04:

```
pip install build
python3 -m build
```

**Comment by brobr** [comment]
Hi; my excuses for the late response.  "oldest-supported-numpy" as module does not work for Slackware64 when building from source. This because the wrong numpy-version (different from what is actually installed), is being 'taken as valid' by this module for Slackware64; so things go wrong. 

Luckily, a simple edit of the toml file made it work.
