### ISSUE TITLE
Python 3.5 not supported for conda installs

### ISSUE THREAD

**Issue by lzamparo** [bxlab/bx-python#9]
For a linux-64 python 3.5.1 environment, the conda install instructions fail:

 `[zamparol@machine]$ python --version
Python 3.5.1 :: Anaconda 2.4.1 (64-bit)`

`[zamparol@machine]$ conda --version
conda 4.1.11`

> [zamparol@machine]$ conda install -c bioconda bx-python
> Fetching package metadata .........
> Solving package specifications: ....
> 
> The following specifications were found to be in conflict:
> - bx-python
> - python 3.5*
>   Use "conda info <package>" to see the dependencies for each package.

This is strange, since `setup.py` requires Python version 3.3 greater?  A quick scan of the bioconda repo [shows](https://github.com/bioconda/bioconda-recipes/issues/1639) I'm not the first to encounter this error.  Have you successfully built & deployed on python3 using conda?

**Comment by jxtx** [comment]
Python 3 support in bx-python is incomplete (only recently begun). It is
not in any released version, which is what conda packages are built from.

**Comment by adamlabadorf** [comment]
What is the status of your complete python3 support effort? I recently worked my way through porting most of bx-python to python3 such that almost all of the tests pass (I couldn't figure out bgzf, the rest passes on python 3.5 and 3.6). If it might be helpful, I'd be happy to make a pull request.

**Comment by jxtx** [comment]
That would be awesome! If bgzf is the only part that doesn't work I can
look at it.

**Comment by TomSmithCGAT** [comment]
Would be brilliant to see bx-python available for python3

**Comment by nsoranzo** [comment]
bx-python has been available for Python 3 for some months now, closing.
